#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=env.sh
source "${SCRIPT_DIR}/env.sh"

activate_emsdk

rm -rf "${ADOBE_PLUGIN_WASM_PREFIX}-build" "${ADOBE_PLUGIN_WASM_PREFIX}"

emcmake cmake \
  -S "${ADOBE_PLUGIN_REPO}" \
  -B "${ADOBE_PLUGIN_WASM_PREFIX}-build" \
  -DCMAKE_INSTALL_PREFIX="${ADOBE_PLUGIN_WASM_PREFIX}" \
  -DCMAKE_BUILD_TYPE=Release \
  -Dpxr_ROOT="${OPENUSD_WASM_PREFIX}" \
  -Dpxr_DIR="${OPENUSD_WASM_PREFIX}" \
  -DCMAKE_PREFIX_PATH="${OPENUSD_WASM_PREFIX}" \
  -DCMAKE_FIND_ROOT_PATH="${OPENUSD_WASM_PREFIX}" \
  -DPXR_FIND_TBB_IN_CONFIG=OFF \
  -DTBB_INCLUDE_DIRS="${OPENUSD_WASM_PREFIX}/include" \
  -DTBB_tbb_LIBRARY_RELEASE="${OPENUSD_WASM_PREFIX}/lib/libtbb.a" \
  -DTBB_tbbmalloc_LIBRARY_RELEASE="${OPENUSD_WASM_PREFIX}/lib/libtbbmalloc.a" \
  -DZLIB_ROOT="${OPENUSD_WASM_PREFIX}" \
  -DUSD_FILEFORMATS_BUILD_TESTS=OFF \
  -DUSD_FILEFORMATS_ENABLE_FBX=OFF \
  -DUSD_FILEFORMATS_ENABLE_GLTF=ON \
  -DUSD_FILEFORMATS_ENABLE_OBJ=OFF \
  -DUSD_FILEFORMATS_ENABLE_PLY=OFF \
  -DUSD_FILEFORMATS_ENABLE_SPZ=OFF \
  -DUSD_FILEFORMATS_ENABLE_STL=OFF \
  -DUSD_FILEFORMATS_ENABLE_SBSAR=OFF \
  -DUSD_FILEFORMATS_ENABLE_DRACO=OFF \
  -DUSD_FILEFORMATS_ENABLE_OPENIMAGEIO=OFF \
  -DUSD_FILEFORMATS_FETCH_TINYGLTF=ON \
  -DUSD_FILEFORMATS_FETCH_ZLIB=OFF \
  -DUSD_FILEFORMATS_ENABLE_MTLX=ON \
  -DCMAKE_CXX_FLAGS="-pthread --use-port=zlib" \
  -DCMAKE_C_FLAGS="-pthread --use-port=zlib" \
  -DCMAKE_EXE_LINKER_FLAGS="-pthread"

cmake --build "${ADOBE_PLUGIN_WASM_PREFIX}-build" \
  --config Release \
  --target usdGltf \
  --parallel "${BUILD_PARALLELISM:-8}"

cmake --install "${ADOBE_PLUGIN_WASM_PREFIX}-build" \
  --config Release
