#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=env.sh
source "${SCRIPT_DIR}/env.sh"

activate_emsdk

rm -rf "${OPENUSD_WASM_HYDRA_BUILD_DIR}" "${OPENUSD_WASM_HYDRA_PREFIX}"

emcmake cmake \
  -S "${OPENUSD_ROOT}" \
  -B "${OPENUSD_WASM_HYDRA_BUILD_DIR}" \
  -DCMAKE_INSTALL_PREFIX="${OPENUSD_WASM_HYDRA_PREFIX}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DPXR_BUILD_MONOLITHIC=ON \
  -DPXR_ENABLE_PYTHON_SUPPORT=OFF \
  -DPXR_BUILD_TESTS=OFF \
  -DPXR_BUILD_EXAMPLES=OFF \
  -DPXR_BUILD_TUTORIALS=OFF \
  -DPXR_BUILD_USD_TOOLS=OFF \
  -DPXR_BUILD_USDVIEW=OFF \
  -DPXR_BUILD_USD_VALIDATION=OFF \
  -DPXR_BUILD_EXEC=OFF \
  -DPXR_BUILD_IMAGING=ON \
  -DPXR_BUILD_USD_IMAGING=ON \
  -DPXR_BUILD_HD_EMSCRIPTEN=ON \
  -DPXR_ENABLE_GL_SUPPORT=OFF \
  -DPXR_ENABLE_METAL_SUPPORT=OFF \
  -DPXR_ENABLE_VULKAN_SUPPORT=OFF \
  -DPXR_ENABLE_MATERIALX_SUPPORT=OFF \
  -DPXR_ENABLE_OPENVDB_SUPPORT=OFF \
  -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF \
  -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF \
  -DPXR_BUILD_EMBREE_PLUGIN=OFF \
  -DPXR_BUILD_PRMAN_PLUGIN=OFF \
  -DPXR_BUILD_ALEMBIC_PLUGIN=OFF \
  -DPXR_BUILD_DRACO_PLUGIN=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_FIND_ROOT_PATH="${OPENUSD_WASM_PREFIX}" \
  -DOpenSubdiv_DIR="${OPENUSD_WASM_PREFIX}/lib/cmake/OpenSubdiv" \
  -DTBB_INCLUDE_DIRS="${OPENUSD_WASM_PREFIX}/include" \
  -DTBB_tbb_LIBRARY_RELEASE="${OPENUSD_WASM_PREFIX}/lib/libtbb.a" \
  -DTBB_tbbmalloc_LIBRARY_RELEASE="${OPENUSD_WASM_PREFIX}/lib/libtbbmalloc.a" \
  -DOPENSUBDIV_INCLUDE_DIR="${OPENUSD_WASM_PREFIX}/include" \
  -DOPENSUBDIV_OSDCPU_LIBRARY="${OPENUSD_WASM_PREFIX}/lib/libosdCPU.a" \
  -DOPENSUBDIV_OSDGPU_LIBRARY="${OPENUSD_WASM_PREFIX}/lib/libosdGPU.a" \
  -DCMAKE_CXX_FLAGS="-pthread --use-port=zlib" \
  -DCMAKE_C_FLAGS="-pthread --use-port=zlib" \
  -DCMAKE_EXE_LINKER_FLAGS="-pthread"
