#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=env.sh
source "${SCRIPT_DIR}/env.sh"

activate_emsdk

if [[ ! -d "${MATERIALX_WASM_OPENUSD_PREFIX}" ]]; then
  echo "MaterialX wasm prefix not found: ${MATERIALX_WASM_OPENUSD_PREFIX}" >&2
  echo "Run ${SCRIPT_DIR}/build-wasm-materialx-openusd.sh first." >&2
  exit 1
fi

gltf_plugin_args=()
if [[ -d "${ADOBE_PLUGIN_WASM_PREFIX}" ]]; then
  gltf_plugin_args=(
    -DPXR_HD_EMSCRIPTEN_GLTF_PLUGIN_PREFIX="${ADOBE_PLUGIN_WASM_PREFIX}"
    -DPXR_HD_EMSCRIPTEN_GLTF_DRACO=ON
  )
fi

git_sha() {
  git -C "$1" rev-parse HEAD 2>/dev/null || true
}

git_dirty() {
  if git -C "$1" diff --quiet --ignore-submodules HEAD -- 2>/dev/null; then
    echo false
  else
    echo true
  fi
}

emscripten_version="$(emcc --version | sed -n '1p')"

rm -rf "${OPENUSD_WASM_HYDRA_MTLX_BUILD_DIR}" "${OPENUSD_WASM_HYDRA_MTLX_PREFIX}"

emcmake cmake \
  -S "${OPENUSD_ROOT}" \
  -B "${OPENUSD_WASM_HYDRA_MTLX_BUILD_DIR}" \
  -DCMAKE_INSTALL_PREFIX="${OPENUSD_WASM_HYDRA_MTLX_PREFIX}" \
  -DCMAKE_BUILD_TYPE=Release \
  -DPXR_BUILD_MONOLITHIC=ON \
  -DPXR_ENABLE_PYTHON_SUPPORT=OFF \
  -DPXR_BUILD_TESTS=OFF \
  -DPXR_BUILD_EXAMPLES=OFF \
  -DPXR_BUILD_TUTORIALS=OFF \
  -DPXR_BUILD_USD_TOOLS=OFF \
  -DPXR_BUILD_USDVIEW=OFF \
  -DPXR_BUILD_USD_VALIDATION=OFF \
  -DPXR_BUILD_EXEC=OFF \
  -DPXR_BUILD_IMAGING=ON \
  -DPXR_BUILD_USD_IMAGING=ON \
  -DPXR_BUILD_HD_EMSCRIPTEN=ON \
  "${gltf_plugin_args[@]}" \
  -DPXR_ENABLE_GL_SUPPORT=OFF \
  -DPXR_ENABLE_METAL_SUPPORT=OFF \
  -DPXR_ENABLE_VULKAN_SUPPORT=OFF \
  -DPXR_ENABLE_MATERIALX_SUPPORT=ON \
  -DPXR_ENABLE_OPENVDB_SUPPORT=OFF \
  -DPXR_BUILD_OPENIMAGEIO_PLUGIN=OFF \
  -DPXR_BUILD_OPENCOLORIO_PLUGIN=OFF \
  -DPXR_BUILD_EMBREE_PLUGIN=OFF \
  -DPXR_BUILD_PRMAN_PLUGIN=OFF \
  -DPXR_BUILD_ALEMBIC_PLUGIN=OFF \
  -DPXR_BUILD_DRACO_PLUGIN=OFF \
  -DBUILD_SHARED_LIBS=OFF \
  -DCMAKE_PREFIX_PATH="${MATERIALX_WASM_OPENUSD_PREFIX}" \
  -DMaterialX_DIR="${MATERIALX_WASM_OPENUSD_PREFIX}/lib/cmake/MaterialX" \
  -DPXR_HD_EMSCRIPTEN_MATERIALX_REPO_SHA="$(git_sha "${MATERIALX_REPO}")" \
  -DHD_EMSCRIPTEN_MATERIALX_REPO_DIRTY="$(git_dirty "${MATERIALX_REPO}")" \
  -DPXR_HD_EMSCRIPTEN_GLTF_PLUGIN_REPO_SHA="$(git_sha "${ADOBE_PLUGIN_REPO}")" \
  -DHD_EMSCRIPTEN_GLTF_PLUGIN_REPO_DIRTY="$(git_dirty "${ADOBE_PLUGIN_REPO}")" \
  -DPXR_HD_EMSCRIPTEN_EMSCRIPTEN_VERSION="${emscripten_version}" \
  -DPXR_HD_EMSCRIPTEN_EMSDK_SHA="$(git_sha "${EMSDK_DIR}")" \
  -DHD_EMSCRIPTEN_EMSDK_DIRTY="$(git_dirty "${EMSDK_DIR}")" \
  -DMATERIALX_STDLIB_DIR="${MATERIALX_WASM_OPENUSD_PREFIX}/libraries" \
  -DCMAKE_FIND_ROOT_PATH="${OPENUSD_WASM_PREFIX};${MATERIALX_WASM_OPENUSD_PREFIX}" \
  -DOpenSubdiv_DIR="${OPENUSD_WASM_PREFIX}/lib/cmake/OpenSubdiv" \
  -DTBB_INCLUDE_DIRS="${OPENUSD_WASM_PREFIX}/include" \
  -DTBB_tbb_LIBRARY_RELEASE="${OPENUSD_WASM_PREFIX}/lib/libtbb.a" \
  -DTBB_tbbmalloc_LIBRARY_RELEASE="${OPENUSD_WASM_PREFIX}/lib/libtbbmalloc.a" \
  -DOPENSUBDIV_INCLUDE_DIR="${OPENUSD_WASM_PREFIX}/include" \
  -DOPENSUBDIV_OSDCPU_LIBRARY="${OPENUSD_WASM_PREFIX}/lib/libosdCPU.a" \
  -DOPENSUBDIV_OSDGPU_LIBRARY="${OPENUSD_WASM_PREFIX}/lib/libosdGPU.a" \
  -DCMAKE_CXX_FLAGS="-pthread --use-port=zlib" \
  -DCMAKE_C_FLAGS="-pthread --use-port=zlib" \
  -DCMAKE_EXE_LINKER_FLAGS="-pthread"
